name: Run Tests

on:
  push:

jobs:
  run-tests:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - name: Install and run tests
        run: |
          npm install
          npm run ci
